FROM debian:latest

# Copy the script for installing dependencies
COPY requirements.sh /tmp/

# Set executable permissions for the script and run it with debugging
RUN chmod +x /tmp/requirements.sh && /bin/bash -x /tmp/requirements.sh

# Set environment variables
ARG VSPHERE_USERNAME
ARG VSPHERE_PASSWORD
ARG VSPHERE_SERVER
ARG PLAYBOOK_FILE
ENV VSPHERE_USERNAME=$VSPHERE_USERNAME \
    VSPHERE_PASSWORD=$VSPHERE_PASSWORD \
    VSPHERE_SERVER=$VSPHERE_SERVER \
    PATH="/venv/bin:$PATH"

# Clone the Git repository
RUN git clone https://github.com/shellymiron/smiron-ans-vm /ansible

# Set working directory and create ansible.cfg
WORKDIR /ansible
RUN echo "[defaults]\nansible_python_interpreter=/venv/bin/python3" > ansible.cfg

# Run Ansible playbook
CMD ansible-playbook -e ansible_python_interpreter=/venv/bin/python3 $PLAYBOOK_FILE

